name: "Configure the user for git as the GitHub Actions Bot"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -ex
        bot_id=$(curl -s 'https://api.github.com/users/github-actions%5Bbot%5D' | sed -n '/"id"/s/[^0-9]*\([0-9]\+\).*/\1/p')
        git config --global user.name 'GitHub Actions'
        git config --global user.email "${bot_id}+github-actions[bot]@users.noreply.github.com"
